# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChapMan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChapMan

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'

  target 'ChapManTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChapManUITests' do
    # Pods for testing
  end

end
